on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - name: copy code from repo
        uses: actions/checkout@v4
      
      - name: see the files
        run: ls
      
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: install dependencies
        run: npm install 
      
      - name: run tests
        run: echo "There is no tests"